name: Demo
run-name: Demo is cool
on: 
  push:
    branches: [ main ]
jobs:
    Convert-yaml:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.10.11
            
            - name: Get File
              run: |
                cd ${{ github.workspace }}
                curl -fssL https://github.com/Nathan3-14/yaml-mindmap/blob/main/convert.py?raw=true | echo > ./mindmaps/electricity/convert.py
            
            - name: Execute
              run: |
                python ./mindmaps/electricity/convert.py

            - name: Get File
              run: |
                ls ./mindmaps/electricity
                echo "   "
                ls
                rm ./mindmaps/electricity/convert.py
              
            - name: Git Setup
              run: |
                git config user.name "GitHub Actions Bot"
                git config user.email "<>"

            - name: Git
              run: |
                ls ./
                git add ./output.md
                git commit -m "(action) Updated output.md"
                git push origin master