name: Demo
run-name: Demo is cool
on: [push]
jobs:
    Convert-yaml:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo
              uses: actions/checkout@v4
            - run: cd ${{ github.workspace }}
            - run: touch test.file
            - name: curl -fssL https://github.com/Nathan3-14/yaml-mindmap/blob/main/convert.py?raw=true
            - run: ls