name: Demo
run-name: ${{ github.actor }} demo
on: [push]
jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Cool test!"
            - name: Check out repo code?
            - uses: actions/checkout@v4
            - run: ls ${{ github.workspace }}