name: Git Branch Test
run-name: Git Branch
on:
  push
        
jobs:
  Fix-Html:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
    
      - name: Create new branch
        run: |
          git branch Test
          git branch
    
            